name: CI

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_DATABASE: beverly_test
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, pdo_mysql, exif, pcntl, bcmath, fileinfo

      - run: cp .env.example .env

      - run: composer install --prefer-dist --no-progress

      - run: php artisan key:generate

      - run: php artisan migrate --force
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: beverly_test
          DB_USERNAME: user
          DB_PASSWORD: password

      - run: php artisan test
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: beverly_test
          DB_USERNAME: user
          DB_PASSWORD: password

      - run: composer install --prefer-dist --no-progress --no-suggest
      - run: vendor/bin/phpcs --standard=PSR12 --colors -n src tests
